[package]
name = "csta_montecarlo"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
description = "Adds montecarlo iterator to randomly generate instances of a randomizable struct"
keywords = ["monte-carlo", "random"]

[dependencies]
rand = "=0.10.2"
csta_core = { path = "../csta_core", version = "^3.0.0" }

rand_pcg = { version = "=0.10.2", optional = true, features = ["serde"] }
[features]
checkpoint = ["dep:rand_pcg"]
